# docker build -t imdb_refresh_service . -f Dockerfile_MOVIELIB_imdb
FROM ghcr.io/linuxserver/transmission

LABEL Author="Mikael"

# Copy files
COPY torr_service/finished_torrent_routine.py ./
COPY torr_service/torr_finished_routine.sh ./
# Set run rights -i know they're too broad but fk it
RUN chmod 777 finished_torrent_routine.py
RUN chmod 777 torr_finished_routine.sh

# Add routine to change transmission settings.
COPY torr_service/change_transmission_settings.sh ./config/custom-cont-init.d/
RUN chmod +x ./config/custom-cont-init.d/change_transmission_settings.sh
RUN chmod 777 ./config/custom-cont-init.d/change_transmission_settings.sh


RUN jq '."script-torrent-done-enabled" = true' /defaults/settings.json
RUN jq '."script-torrent-done-filename" = "/torr_finished_routine.sh"' /defaults/settings.json
# test 1231
RUN jq '."incomplete-dir-enabled" = false' /defaults/settings.json
