# docker build -t mikael6/mad_repo:imdb_update_service . -f Dockerfile_imdb_db_update_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY db_services/ ./
COPY utils.py ./


RUN pip install -r requirements.txt


ENTRYPOINT ["python", "master_scheduler.py"]
