# docker build -t download_imdb . -f Dockerfile_MOVIELIB_imdb
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY db_services/imdb_dump_import.py ./
COPY db_services/refresh_imdb_db.py ./
COPY utils.py ./


COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "refresh_imdb_db.py"]
