# docker build -t imdb_refresh_service . -f Dockerfile_MOVIELIB_imdb
FROM ghcr.io/linuxserver/transmission

LABEL Author="Mikael"

# Copy files
COPY torr_service/finished_torrent_routine.py ./
COPY torr_service/torr_finished_routine.sh ./
# Set run rights -i know they're too broad but fk it
RUN chmod 777 finished_torrent_routine.py
RUN chmod 777 torr_finished_routine.sh

ENV script_torrent_done_enabled=true
ENV script_torrent_done_filename="/torr_finished_routine.sh"
ENV incomplete_dir_enabled=false

RUN jq '."script-torrent-done-enabled" = true' /defaults/settings.json
RUN jq '."script-torrent-done-filename" = "/torr_finished_routine.sh"' /defaults/settings.json
# test 1231
RUN jq '."incomplete-dir-enabled" = false' /defaults/settings.json
