# docker build -t newsletter_service . -f Dockerfile_filelist_service
FROM python:3.10

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY newsletter_service/ ./
COPY utils.py ./

RUN pip install -r requirements.txt


ENTRYPOINT ["python", "newsletter_routine.py"]
