# docker build -t imdb_refresh_service . -f Dockerfile_MOVIELIB_imdb
FROM ghcr.io/linuxserver/transmission

LABEL Author="Mikael"

# Copy files
COPY torrent_db_refresher/finished_torrent_routine.py ./
COPY torrent_db_refresher/torr_finished_routine.sh ./
# Set run rights -i know they're too broad but fk it
RUN chmod 777 finished_torrent_routine.py
RUN chmod 777 torr_finished_routine.sh
