# docker build -t torrent_service . -f Dockerfile_torrent_service
FROM python:3.10

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY telegram_service/ ./

COPY telegram_service/images ./images
COPY utils.py ./


RUN pip install -r requirements.txt

EXPOSE 9092

ENTRYPOINT ["python", "bot.py"]
