# docker build -t imdb_refresh_service . -f Dockerfile_MOVIELIB_imdb
FROM ghcr.io/linuxserver/transmission

LABEL Author="Mikael"

# Copy files
COPY torr_service/finished_torrent_routine.py ./
COPY torr_service/torr_finished_routine.sh ./
# Set run rights -i know they're too broad but fk it
RUN chmod 777 finished_torrent_routine.py
RUN chmod 777 torr_finished_routine.sh

ENV TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=true
ENV TRANSMISSION_SCRIPT_TORRENT_DONE-FILENAME="/torr_finished_routine.sh"
ENV TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
