# docker build -t imdb_refresh_service . -f Dockerfile_imdb_db_update_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY db_services/imdb_dump_import.py ./
COPY db_services/refresh_imdb_db.py ./
COPY settings.py ./
COPY utils.py ./
COPY db_services/last_update.txt ./


COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "refresh_imdb_db.py"]
