# docker build -t torrent_service . -f Dockerfile_torrent_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY torr_service/server.py ./
COPY torr_service/torr_service_utils.py ./
COPY utils.py ./


COPY requirements.txt ./
RUN pip install -r requirements.txt

EXPOSE 9092

ENTRYPOINT ["python", "server.py"]
