# docker build -t mikael6/mad_repo:imdb_update_service . -f Dockerfile_imdb_db_update_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY db_services/master_scheduler.py ./
COPY db_services/imdb_dump_import.py ./
COPY db_services/refresh_imdb_db.py ./
COPY db_services/refresh_omdb_db.py ./
COPY db_services/refresh_tmdb_db.py ./
COPY utils.py ./


COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "master_scheduler.py"]
