# docker build -t filelist_service . -f Dockerfile_filelist_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY filelist_service/filelist_routine.py ./
COPY filelist_service/email_tools.py ./
COPY utils.py ./


COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "filelist_routine.py"]
