# docker build -t imdb_refresh_service . -f Dockerfile_MOVIELIB_imdb
FROM python:3.10

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY myimdb_service/ ./
COPY utils.py ./

RUN pip install -r requirements.txt


ENTRYPOINT ["python", "sync_services.py"]
