# docker build -t filelist_service . -f Dockerfile_filelist_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY filelist_service/filelist_routine.py ./
COPY db_tools.py ./
COPY filelist_service/email_tools.py ./
COPY utils3.py ./
COPY settings.py ./
COPY torr_tools.py ./
COPY tmdb_omdb_tools.py ./
COPY plex_utils.py ./
COPY views ./views
COPY crypto_tools.py ./

COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "filelist_routine.py"]
