# docker build -t omdb_service . -f Dockerfile_omdb_db_update_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY db_services/refresh_omdb_db.py ./
COPY tmdb_omdb_tools.py ./
COPY settings.py ./
COPY utils3.py ./
COPY db_services/last_update.txt ./
COPY tmdb_omdb_tools.py ./


COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "refresh_omdb_db.py"]
