# docker build -t omdb_service . -f Dockerfile_omdb_db_update_service
FROM python:3.9.1

LABEL Author="Mikael"

RUN mkdir /app
WORKDIR /app

COPY db_services/refresh_omdb_db.py ./
COPY db_services/db_services_utils.py ./
COPY utils.py ./


COPY requirements.txt ./
RUN pip install -r requirements.txt


ENTRYPOINT ["python", "refresh_omdb_db.py"]
